# The URL the site will be built for
base_url = "https://tylerjw.dev"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "terminimal"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
logo_text = "Tyler Weaver"
author = "Tyler Weaver"
github = "tylerjw"
accent_color = "orange-light"
background_color = "light"
menu_items = [
    {name = "blog", url = "$BASE_URL"},
    {name = "github", url = "https://github.com/tylerjw", newtab = true},
]
default_language = "en"
page_titles = "combined"
