apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nameOverride }}-config
  namespace: default
data:
  nginx.conf: |
    server {
        listen {{ .Values.service.port }};
        server_name localhost;
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
    }
  app.properties: |
    app.name={{ .Values.nameOverride }}
    app.replicas={{ .Values.replicaCount }}
    app.image={{ .Values.image.repository }}:{{ .Values.image.tag }}
