apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nameOverride }}-config
  namespace: default
data:
  redis.conf: |
    maxmemory {{ .Values.config.maxmemory }}
    maxmemory-policy {{ .Values.config.maxmemoryPolicy }}
    timeout {{ .Values.config.timeout }}
    bind 0.0.0.0
    port {{ .Values.service.port }}

  startup.sh: |
    #!/bin/bash
    echo "Starting Redis with config: {{ .Values.nameOverride }}"
    redis-server /etc/redis/redis.conf
