name: Rust/C++ Interop Example

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.9.0
        with:
          pixi-version: v0.55.0
          cache: true

      - run: pixi run interop-example
